---

- name: copy service definition for Jenkins
  template:
    src: jenkins.service
    dest: "/etc/systemd/system/jenkins.service"
    mode: 0644
    owner: root
    group: root

- name: copy executable for Jenkins
  template:
    src: jenkins
    dest: "/usr/local/bin/jenkins"
    mode: 0755
    owner: root
    group: root

- name: start jenkins
  service:
    name: jenkins
    state: started
    enabled: true

- name: sleep
  pause:
    seconds: 10

- name: install jenkins plugins
  shell: docker exec jenkins /bin/bash -c 'java -jar /opt/jenkins-plugin-manager.jar --war /usr/share/jenkins/jenkins.war --plugin-file /tmp/jenkins/plugins.txt -d /var/jenkins_home/plugins/'
  changed_when: true

- name: restart jenkins
  service:
    name: jenkins
    state: restarted

- name: Ensure Java is installed.
  apt:
    name: "{{ java_packages }}"
    state: present
