---

- name: copy service definition for Jenkins
  template:
    src: jenkins.service
    dest: "/etc/systemd/system/jenkins.service"
    mode: 0644
    owner: root
    group: root

- name: copy executable for Jenkins
  template:
    src: jenkins
    dest: "/usr/local/bin/jenkins"
    mode: 0755
    owner: root
    group: root

- name: start jenkins
  service:
    name: jenkins
    state: started

- name: sleep
  pause:
    seconds: 10

- name: install jenkins plugins
  shell: docker exec jenkins /bin/bash -c '/usr/local/bin/install-plugins.sh <  /tmp/jenkins/plugins.txt'
  changed_when: true

- name: setup jenkins plugins
  shell: docker exec jenkins /bin/bash -c 'mv /usr/share/jenkins/ref/plugins/*.jpi /var/jenkins_home/plugins/'
  changed_when: true

- name: restart jenkins
  service:
    name: jenkins
    state: restarted
