---

- name: transfer jenkins configuration
  template:
    src: "{{ item }}"
    dest: "{{ nginx_opt_dir }}/sites-enabled/{{ item | basename }}"
  with_fileglob:
    - ../templates/sites-enabled/*.*
  notify:
    - restart nginx
