---

- name: Setup group
  ansible.builtin.group:
    name: "{{ jenkins_group }}"
    system: false

- name: Setup user
  ansible.builtin.user:
    name: "{{ jenkins_user }}"
    system: false
    group: "{{ jenkins_group }}"
