---

- name: restart jenkins
  service:
    name: "jenkins.service"
    state: restarted
    enabled: true

- name: Restart Nginx
  service:
    name: "nginx.service"
    state: restarted
    enabled: true
