---

- name: Restart jenkins
  ansible.builtin.service:
    name: "jenkins.service"
    state: restarted
    enabled: true

- name: Restart Nginx
  ansible.builtin.service:
    name: "nginx.service"
    state: restarted
    enabled: true
